version: '3.4'

services:
  projetospessoais.provedordados.api:
    image: ${DOCKER_REGISTRY-}projetospessoaisprovedordadosapi
    build:
      context: .
      dockerfile: ProjetosPessoais.ProvedorDados.API/Dockerfile
